services:

  # Datenbanken
  db-redis:
    image: redis:${IMAGE_VERSION_REDIS:-7-alpine}
    container_name: db-redis
    networks:
      - datenbanken
      - debug-tools
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Debug Tools
  debug-redisinsight:
    image: redis/redisinsight:${IMAGE_VERSION_REDISINSIGHT:-latest}
    container_name: debug-redisinsight
    networks:
      - debug-tools
      - proxy
    ports:
      - "8001:8001"
    depends_on:
      db-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5540/api/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Anwendungen
  rag-frontend:
    image: ghcr.io/staincabler/dhbw_tif23_rag-frontend:${IMAGE_VERSION_FRONTEND:-main}
    container_name: rag-frontend
    networks:
      - application
      - proxy
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_USE_MOCK=${VITE_USE_MOCK}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_APP_FOOTER=${VITE_APP_FOOTER}
      - VITE_APP_RELEASE=${VITE_APP_RELEASE}
      - VITE_DEFAULT_THEME=${VITE_DEFAULT_THEME}
      - VITE_DEFAULT_PALETTE=${VITE_DEFAULT_PALETTE}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.ptb-rag.rule=Host(`${FQDN_RAG}`)"
      - "traefik.http.routers.ptb-rag.entrypoints=websecure"
      - "traefik.http.routers.ptb-rag.tls.certresolver=cloudflare"
      - "traefik.http.services.ptb-rag.loadbalancer.server.port=3000"
    depends_on:
#      rag-backend:
      db-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  rag-backend:
    image: ghcr.io/staincabler/dhbw_tif23_rag-backend:${IMAGE_VERSION_BACKEND:-main}
    container_name: rag-backend
    networks:
      - application
      - internet
      - datenbanken
    environment:
      - REDIS_HOST=db-redis
      - REDIS_PORT=6379
    depends_on:
      db-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  internet:
    driver: bridge
    internal: false
    attachable: false
    name: internet_rag-system
  proxy:
    external: true
    name: proxy-network
  application:
    driver: bridge
    internal: true
    attachable: false
    name: internal_application
  datenbanken:
    driver: bridge
    internal: true
    attachable: false
    name: internal_datenbanken
  debug-tools:
    driver: bridge
    internal: true
    attachable: false
    name: internal_debug-tools